problems:
    - config_path: "./PROBLEMS/knapsack/config.py"
      instance_path: "./PROBLEMS/knapsack/instances"
      instance_url: "https://asdfadsfgdsfg.com/instances"
      assets_path: "./PROBLEMS/knapsack/assets"
      assets_url: "https://asdfadsfgdsfg.com/assets"
      solution_path: "./PROBLEMS/knapsack/solutions"
      solution_url: "https://asdfadsfgdsfg.com/solutions"
    - config_path: "./PROBLEMS/multi_knapsack/config.py"
      instance_path: "./PROBLEMS/multi_knapsack/instances"
      instance_url: "https://asdfadsfgdsfg.com/instances"
      assets_path: "./PROBLEMS/multi_knapsack/assets"
      assets_url: "https://asdfadsfgdsfg.com/assets"
      solution_path: "./PROBLEMS/multi_knapsack/solutions"
      solution_url: "https://asdfadsfgdsfg.com/solutions"
database: "sqlite:///database.db"
api_key: "asdfasdfasdf"